import { Octokit } from "@octokit/rest";
import { applyPatch } from "diff";
import { getFileContent } from "./repos.js";

// ----------------------------------------
// Types
// ----------------------------------------

export interface FileDiff {
  file: string;  // repo-relative path, e.g. "src/services/auth.ts"
  patch: string; // unified diff string
}

export interface CreatePROptions {
  owner: string;
  repo: string;
  baseBranch: string;
  title: string;
  body?: string;
  diffs: FileDiff[];
}

export interface CreatedPR {
  url: string;
  number: number;
  branch: string;
}

// ----------------------------------------
// Create branch name from title + timestamp
// e.g. "ADE/add-rate-limiting-1712345678"
// ----------------------------------------

function branchName(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  return `ADE/${slug}-${Math.floor(Date.now() / 1000)}`;
}

// ----------------------------------------
// Main: create branch → commit all diffs → open PR
// ----------------------------------------

export async function createBranchAndPR(
  octokit: Octokit,
  options: CreatePROptions
): Promise<CreatedPR> {
  const { owner, repo, baseBranch, title, body = "", diffs } = options;
  const branch = branchName(title);

  // 1. Resolve base branch SHA
  const { data: baseRef } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });
  const baseSha = baseRef.object.sha;

  // 2. Create the new branch
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branch}`,
    sha: baseSha,
  });

  // 3. Commit each changed file onto the new branch
  for (const diff of diffs) {
    await commitFileDiff(octokit, owner, repo, branch, diff);
  }

  // 4. Open the PR
  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    head: branch,
    base: baseBranch,
    title,
    body: body || `Generated by ADE\n\n${diffs.map((d) => `- \`${d.file}\``).join("\n")}`,
  });

  return {
    url: pr.html_url,
    number: pr.number,
    branch,
  };
}

// ----------------------------------------
// Apply a unified diff patch to the current file content,
// then commit the result to the given branch.
// ----------------------------------------

async function commitFileDiff(
  octokit: Octokit,
  owner: string,
  repo: string,
  branch: string,
  diff: FileDiff
): Promise<void> {
  // Try to get the current file (may not exist for new files)
  let currentContent = "";
  let currentSha: string | undefined;

  try {
    const file = await getFileContent(octokit, owner, repo, diff.file, branch);
    currentContent = file.content;
    currentSha = file.sha;
  } catch {
    // File does not exist yet — this is a new file addition
  }

  const newContent = applyPatch(currentContent, diff.patch);

  if (newContent === false) {
    throw new Error(`Failed to apply patch to ${diff.file} — patch does not match current content`);
  }

  const encodedContent = Buffer.from(newContent).toString("base64");

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: diff.file,
    message: `ADE: update ${diff.file}`,
    content: encodedContent,
    branch,
    ...(currentSha ? { sha: currentSha } : {}),
  });
}
